
project_id = "oymlikmotraabukjqkkx"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.payment-retry]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false
