/**
 * VAT201 PDF Service
 * Handles generation and management of VAT201 PDF documents
 */

import { VAT201Return } from './vatCalculationService';

class VAT201PDFService {
  private static instance: VAT201PDFService;
  private readonly PDF_STORAGE_KEY = 'vat201_pdfs';

  public static getInstance(): VAT201PDFService {
    if (!VAT201PDFService.instance) {
      VAT201PDFService.instance = new VAT201PDFService();
    }
    return VAT201PDFService.instance;
  }

  /**
   * Generate VAT201 PDF from return data
   */
  async generateVAT201PDF(vatReturn: VAT201Return): Promise<string> {
    try {
      // In a real implementation, this would use a PDF library like jsPDF or PDFKit
      // For now, we'll create a simple HTML-based PDF content
      const pdfContent = this.generatePDFContent(vatReturn);
      
      // Store the PDF content (in a real app, this would be a proper PDF blob)
      const pdfId = `vat201-pdf-${vatReturn.id}`;
      this.storePDFContent(pdfId, pdfContent);
      
      return pdfId;
    } catch (error) {
      console.error('Error generating VAT201 PDF:', error);
      throw new Error('Failed to generate VAT201 PDF');
    }
  }

  /**
   * Generate PDF content as HTML (mock implementation)
   */
  private generatePDFContent(vatReturn: VAT201Return): string {
    const { calculation } = vatReturn;
    
    return `
<!DOCTYPE html>
<html>
<head>
    <title>VAT201 Return - ${vatReturn.period}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; }
        .section { margin-bottom: 20px; }
        .field { margin-bottom: 10px; }
        .label { font-weight: bold; display: inline-block; width: 200px; }
        .value { display: inline-block; }
        .amount { text-align: right; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .total-row { font-weight: bold; background-color: #f9f9f9; }
    </style>
</head>
<body>
    <div class="header">
        <h1>VAT201 - Value-Added Tax Return</h1>
        <h2>Period: ${vatReturn.period}</h2>
        <p>Return ID: ${vatReturn.id}</p>
        ${vatReturn.referenceNumber ? `<p>Reference: ${vatReturn.referenceNumber}</p>` : ''}
    </div>
    
    <div class="section">
        <h3>Return Information</h3>
        <div class="field">
            <span class="label">Status:</span>
            <span class="value">${vatReturn.status.toUpperCase()}</span>
        </div>
        <div class="field">
            <span class="label">Period:</span>
            <span class="value">${calculation.period}</span>
        </div>
        <div class="field">
            <span class="label">Generated Date:</span>
            <span class="value">${new Date(calculation.createdDate).toLocaleDateString()}</span>
        </div>
        ${vatReturn.submissionDate ? `
        <div class="field">
            <span class="label">Submission Date:</span>
            <span class="value">${new Date(vatReturn.submissionDate).toLocaleDateString()}</span>
        </div>` : ''}
    </div>
    
    <div class="section">
        <h3>VAT Calculation Summary</h3>
        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th class="amount">Amount (R)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Total Sales (VAT Inclusive)</td>
                    <td class="amount">${calculation.totalSales.toFixed(2)}</td>
                </tr>
                <tr>
                    <td>Output VAT (15%)</td>
                    <td class="amount">${calculation.outputVAT.toFixed(2)}</td>
                </tr>
                <tr>
                    <td>Total Purchases (VAT Inclusive)</td>
                    <td class="amount">${calculation.totalPurchases.toFixed(2)}</td>
                </tr>
                <tr>
                    <td>Input VAT (15%)</td>
                    <td class="amount">${calculation.inputVAT.toFixed(2)}</td>
                </tr>
                <tr class="total-row">
                    <td><strong>Net VAT ${calculation.netVAT >= 0 ? 'Payable' : 'Refundable'}</strong></td>
                    <td class="amount"><strong>${Math.abs(calculation.netVAT).toFixed(2)}</strong></td>
                </tr>
            </tbody>
        </table>
    </div>
    
    <div class="section">
        <h3>Declaration</h3>
        <p>I declare that the information furnished in this return is true and correct in every respect.</p>
        <br>
        <p>Signature: ___________________________ Date: _______________</p>
        <br>
        <p>Name: _________________________________ Capacity: _______________</p>
    </div>
    
    <div class="section">
        <p><small>Generated by MOK Mzansi Books VAT Management System</small></p>
        <p><small>Generated on: ${new Date().toLocaleString()}</small></p>
    </div>
</body>
</html>`;
  }

  /**
   * Store PDF content in localStorage
   */
  private storePDFContent(pdfId: string, content: string): void {
    try {
      const pdfs = this.getAllStoredPDFs();
      pdfs[pdfId] = {
        id: pdfId,
        content,
        createdDate: new Date().toISOString(),
        size: content.length
      };
      localStorage.setItem(this.PDF_STORAGE_KEY, JSON.stringify(pdfs));
    } catch (error) {
      console.error('Error storing PDF content:', error);
    }
  }

  /**
   * Get all stored PDFs
   */
  private getAllStoredPDFs(): Record<string, any> {
    try {
      return JSON.parse(localStorage.getItem(this.PDF_STORAGE_KEY) || '{}');
    } catch {
      return {};
    }
  }

  /**
   * Download PDF (mock implementation)
   */
  downloadPDF(pdfId: string, filename: string): void {
    try {
      const pdfs = this.getAllStoredPDFs();
      const pdf = pdfs[pdfId];
      
      if (!pdf) {
        throw new Error('PDF not found');
      }
      
      // Create a blob with the HTML content
      const blob = new Blob([pdf.content], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      
      // Create a temporary link and trigger download
      const link = document.createElement('a');
      link.href = url;
      link.download = filename.replace('.pdf', '.html'); // Since we're generating HTML
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      // Clean up the URL
      URL.revokeObjectURL(url);
      
      console.log(`VAT201 document downloaded: ${filename}`);
    } catch (error) {
      console.error('Error downloading PDF:', error);
      throw new Error('Failed to download VAT201 document');
    }
  }

  /**
   * Get PDF content by ID
   */
  getPDFContent(pdfId: string): string | null {
    try {
      const pdfs = this.getAllStoredPDFs();
      return pdfs[pdfId]?.content || null;
    } catch {
      return null;
    }
  }

  /**
   * Delete PDF by ID
   */
  deletePDF(pdfId: string): void {
    try {
      const pdfs = this.getAllStoredPDFs();
      delete pdfs[pdfId];
      localStorage.setItem(this.PDF_STORAGE_KEY, JSON.stringify(pdfs));
    } catch (error) {
      console.error('Error deleting PDF:', error);
    }
  }

  /**
   * Get PDF metadata
   */
  getPDFMetadata(pdfId: string): { id: string; createdDate: string; size: number } | null {
    try {
      const pdfs = this.getAllStoredPDFs();
      const pdf = pdfs[pdfId];
      if (!pdf) return null;
      
      return {
        id: pdf.id,
        createdDate: pdf.createdDate,
        size: pdf.size
      };
    } catch {
      return null;
    }
  }

  /**
   * Clear all stored PDFs
   */
  clearAllPDFs(): void {
    try {
      localStorage.removeItem(this.PDF_STORAGE_KEY);
    } catch (error) {
      console.error('Error clearing PDFs:', error);
    }
  }
}

const vat201PDFService = VAT201PDFService.getInstance();
export default vat201PDFService;